parameters:
    # Limitation mappers
    ezrepoforms.limitation.null.template: "EzPlatformAdminUiBundle:Limitation:null_limitation_values.html.twig"
    ezrepoforms.limitation.udw.template: "EzPlatformAdminUiBundle:Limitation:udw_limitation_value.html.twig"
