system:
    admin:
        user:
            login_template: "@EzPlatformAdminUi/Security/login.html.twig"
        content_view:
            full:
                default:
                    controller: 'EzPlatformAdminUiBundle\Controller\ContentViewController:locationViewAction'
                    template: "@EzPlatformAdminUi/content/locationview.html.twig"
                    match: true
