services:
    EzSystems\EzPlatformAdminUi\Tab\LocationView\:
        resource: "../../../lib/Tab/LocationView/*"
        parent: EzSystems\EzPlatformAdminUi\Tab\AbstractTab
        public: true
        tags:
            - { name: ezplatform.tab, group: location-view }
