services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzPlatformAdminUiBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    EzPlatformAdminUiBundle\Controller\ContentTypeController:
        public: true
        arguments:
            $contentTypeActionDispatcher: '@ezrepoforms.action_dispatcher.content_type'
