parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\RepositoryForms\Form\Processor\:
        resource: "../../../lib/RepositoryForms/Form/Processor/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }
