services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Menu Builders
    #

    EzSystems\EzPlatformAdminUi\Menu\MainMenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.main }

    EzSystems\EzPlatformAdminUi\Menu\LeftSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content.sidebar_left }
