imports:
    - { resource: tabs/locationview.yml }
    - { resource: tabs/dashboard.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzPlatformAdminUiBundle\Templating\Twig\TabExtension:
        arguments:
            $defaultTemplate: '%ezplatform.content_view.tabs.default_template%'

    EzPlatformAdminUi\Tab\TabRegistry: ~
    EzPlatformAdminUi\Tab\SystemInfo\TabFactory: ~

    EzPlatformAdminUi\Tab\Event\Subscriber\:
        resource: "../../../lib/Tab/Event/Subscriber/*"
        public: true
        tags: ['kernel.event_subscriber']

    EzPlatformAdminUi\Tab\AbstractTab:
        abstract: true
        lazy: true

    EzPlatformAdminUi\Tab\AbstractRouteBasedTab:
        parent: EzPlatformAdminUi\Tab\AbstractTab
        abstract: true
        autowire: true
        autoconfigure: false
        public: false
        lazy: true

    EzPlatformAdminUi\Tab\AbstractControllerBasedTab:
        parent: EzPlatformAdminUi\Tab\AbstractTab
        abstract: true
        autowire: true
        autoconfigure: false
        public: false
        lazy: true
