parameters:
    ezplatform.locale.browser_map:
        au: ['eng-AU']
        be: ['fre-BE']
        br: ['por-BR']
        ca: ['eng-CA']
        cn: ['chi-CN']
        cz: ['cze-CZ']
        de: ['ger-DE']
        dk: ['dan-DK']
        en: ['eng-GB', 'eng-US']
        es: ['esl-ES']
        fi: ['fin-FI']
        fr: ['fre-FR']
        gb: ['eng-GB']
        gr: ['ell-GR']
        hk: ['chi-HK']
        hr: ['cro-HR']
        hu: ['hun-HU']
        id: ['ind-ID']
        il: ['heb-IL']
        in: ['hin-IN']
        it: ['ita-IT']
        jp: ['jpn-JP']
        kr: ['kor-KR']
        mx: ['esl-MX']
        mz: ['por-MZ']
        nl: ['dut-NL']
        no: ['nor-NO']
        nz: ['eng-NZ']
        pl: ['pol-PL']
        pt: ['por-PT']
        rs: ['srp-RS']
        ru: ['rus-RU']
        sa: ['ara-SA']
        se: ['swe-SE']
        sk: ['slk-SK']
        tr: ['tur-TR']
        tw: ['chi-TW']
        ua: ['ukr-UA']

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Translation\Extractor\JavaScriptFileVisitor:
        tags:
            - { name: jms_translation.file_visitor }

    EzSystems\EzPlatformAdminUi\Translation\Extractor\PolicyTranslationExtractor:
        arguments:
            - '%ezpublish.api.role.policy_map%'
        tags:
            - { name: jms_translation.extractor, alias: ez_policy }

    EzSystems\EzPlatformAdminUi\Translation\UserLanguagePreferenceProvider:
        arguments:
            $languageCodesMap: '%ezplatform.locale.browser_map%'
